# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleo < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/dhruvsaxena1998/cleo"
  version "0.1.1"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.1/cleo_0.1.1_darwin_amd64.tar.gz"
      sha256 "69356333007f1667bf76fd15928a2fe576f5239c745a824a06d00ca7c8312a1e"

      define_method(:install) do
        bin.install "cleo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.1/cleo_0.1.1_darwin_arm64.tar.gz"
      sha256 "59ead07c9ed794a895d8ee4d6a1c96312da5168fc4ab8d1504015cd9d1c4f793"

      define_method(:install) do
        bin.install "cleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.1/cleo_0.1.1_linux_amd64.tar.gz"
      sha256 "3ff92359d4d724a62100591042b4b25960f3deb314c42f4b013088e10764a016"
      define_method(:install) do
        bin.install "cleo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.1/cleo_0.1.1_linux_arm64.tar.gz"
      sha256 "d39757ef610c62b9935ebcb661a80355e85de175232b85af4f7962b37ec118c5"
      define_method(:install) do
        bin.install "cleo"
      end
    end
  end

  def caveats
    <<~EOS
      tmux was installed as a dependency of cleo.
      If you uninstall cleo and no longer need tmux, you can remove it with:
        brew uninstall tmux
    EOS
  end

  test do
    system "#{bin}/cleo", "--version"
  end
end
