# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cleo < Formula
  desc "Terminal session manager for AI coding agents"
  homepage "https://github.com/dhruvsaxena1998/cleo"
  version "0.1.0-beta.4"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.0-beta.4/cleo_0.1.0-beta.4_darwin_amd64.tar.gz"
      sha256 "dc06da968601a8ad21012c1a637e78195335236ab8654363744f844518680ed5"

      define_method(:install) do
        bin.install "cleo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.0-beta.4/cleo_0.1.0-beta.4_darwin_arm64.tar.gz"
      sha256 "9c8a7cc71a74600fe229d8c455efd444416f812137930a10cadc636f60a52360"

      define_method(:install) do
        bin.install "cleo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.0-beta.4/cleo_0.1.0-beta.4_linux_amd64.tar.gz"
      sha256 "2687ae03bb562bc24915c63b67073c9c293c0c50ac5579f3c1608f2820916edf"
      define_method(:install) do
        bin.install "cleo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruvsaxena1998/cleo/releases/download/v0.1.0-beta.4/cleo_0.1.0-beta.4_linux_arm64.tar.gz"
      sha256 "21953e6c26d88b1310f47ca16d2a3e3279dc856008ab04c244818ac26b4cb935"
      define_method(:install) do
        bin.install "cleo"
      end
    end
  end

  def caveats
    <<~EOS
      tmux was installed as a dependency of cleo.
      If you uninstall cleo and no longer need tmux, you can remove it with:
        brew uninstall tmux
    EOS
  end

  test do
    system "#{bin}/cleo", "--version"
  end
end
